<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>Logic.LogicDependencyInjection</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\External\HIK_RCS\HIK_RCS.csproj" />
    <ProjectReference Include="..\Authentication\Authentication.csproj" />
    <ProjectReference Include="..\AutomationDevice\AutomationDevice.csproj" />
    <ProjectReference Include="..\BaseInfo\BaseInfo.csproj" />
    <ProjectReference Include="..\Inventory\Inventory.csproj" />
    <ProjectReference Include="..\Label\Label.csproj" />
	<ProjectReference Include="..\Order\Order.csproj" />
    <ProjectReference Include="..\PlanMaterial\PlanMaterial.csproj" /> 
    <ProjectReference Include="..\ProdctOffLine\ProductOffLine.csproj" /> 
    <ProjectReference Include="..\Purchase\Purchase.csproj" /> 
    <ProjectReference Include="..\Report\Report.csproj" />
    <ProjectReference Include="..\ScheduleJob\ScheduleJob.csproj" />
    <ProjectReference Include="..\Sys\Sys.csproj" />
  </ItemGroup>

</Project>
