CREATE TABLE `InvInStorageLabels`(
`CodeString` varchar(100) NOT NULL   COMMENT '标签码字符串' ,
`GoodsId` varchar(50) NOT NULL   COMMENT '物品ID' ,
`GoodsClassifyGroup` varchar(50) NOT NULL   COMMENT '物品类型分组' ,
`WarehouseId` varchar(50) DEFAULT NULL   COMMENT '仓库ID' ,
`ShelfId` varchar(50) DEFAULT NULL   COMMENT '货架ID' ,
`BinId` int NOT NULL   COMMENT '货位ID' ,
`WorkbinId` int NOT NULL   COMMENT '料箱ID' ,
`WorkbinCellId` int NOT NULL   COMMENT '料箱单元格ID' ,
`UnitId` int NOT NULL   COMMENT '单位ID' ,
`UnitName` varchar(50) NOT NULL   COMMENT '单位' ,
`Quantity` float NOT NULL   COMMENT '每个标签对应数量' ,
`PatchNum` varchar(100) DEFAULT NULL   COMMENT '批次号' ,
`Status` varchar(20) NOT NULL   COMMENT '状态' ,
`UpdateUserId` varchar(50) DEFAULT NULL   COMMENT '上次修改人ID' ,
`UpdateUserName` varchar(50) DEFAULT NULL   COMMENT '上次修改人姓名' ,
`UpdateDate` datetime NOT NULL   COMMENT '上次修改时间' ,
`CreateUserId` varchar(50) DEFAULT NULL   COMMENT '创建人ID' ,
`CreateUserName` varchar(50) DEFAULT NULL   COMMENT '创建人姓名' ,
`CreateDate` datetime NOT NULL   COMMENT '创建时间'  , Primary key(`CodeString`))